{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "CustomerCreateFailMessage"
	},
	"Message": "Create New Customer failed: {#ActionResults:CreateNewCustomer/error}!",
	"Title": "Create Customer",
	"OKCaption": "OK"
}