{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "DeleteCustomerFailMessage"
	},
	"Message": "Customer delete failed: {#ActionResults:DeleteCustomerAction/error}.",
	"Title": "Delete Failed",
	"OKCaption": "OK"
}